<footer>
  <p>&copy; Copyright all rights reserved</p>
  <p class="third-color">&nbsp; by Pedro H</p>
</footer>
<script type="text/javascript" src="/js/materialize.min.js"></script>
<script src="/js/global.js" type="module"></script>
<script src="/js/events/submits.js" type="module"></script>
<script src="/js/events/keyups.js" type="module"></script>
<script src="/js/events/clicks.js" type="module"></script>
<script src="/js/events/change.js" type="module"></script>
<script src="/js/routes.js" type="module"></script>
</body>

</html>
