<?php require(__DIR__ . '/../components/Header.phtml') ?>
<div class="container">
  <div class="box" style="flex-direction: column;">
    <h3 class="third-color">Você está perdido?</h3>
    <a href="/" class="waves-light waves-effect btn deep-purple darken-1 dark-color" style="width: 100%; max-width: 200px; margin: 10px 0;">
      Voltar para a home
    </a>
  </div>
</div>
<?php require(__DIR__ . '/../components/Footer.phtml') ?>
